### ISSUE TITLE
Closing curly brace cannot be written

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode-atom-keybindings#40]
Extracted from https://github.com/Microsoft/vscode/issues/36635

From @deiberdev @mnunezdm 

The extension most likely binds keys to `ctrl+alt+...`. This should not be done, as it impairs users that use a non US keyboard layout on Windows.

e.g. Spanish keyboard layout, Latin American keyboard layout

**Comment by auchenberg** [comment]
@deiberdev @mnunezdm I've updated the mappings for folding which seem to be the ones that collide. I don't have a non-us keyboard so you could try to pull master of this extension and help me validate?


https://github.com/Microsoft/vscode-atom-keybindings/commit/546a547eab57b13a9e2746c2f8d3bb2630454add

**Comment by auchenberg** [comment]
@mnunezdm Thanks for trying it out. Did you pull master of this repo or use the published version?

**Comment by mnunezdm** [comment]
Yes, I removed the extension, install it from the pulled version and tried it out and nothing worked

**Comment by usagi** [comment]
I got the same trouble, I cannot input the `}` in some times. Then, I open the DevTool(`> Toggle Developer Tools`) and type `}` key in the situation. I got the `ERR` on my `}` key input timing:

```
ERR Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
    at Object.t.firstNonWhitespaceIndex (file:///C:/Users/usagi/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:221:720)
    at Function.normalizeIndentation (file:///C:/Users/usagi/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1415:974)
    at g.normalizeIndentation (file:///C:/Users/usagi/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1456:466)
    at Function._runAutoIndentType (file:///C:/Users/usagi/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1481:93)
    at Function.typeWithInterceptors (file:///C:/Users/usagi/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1487:475)
    at file:///C:/Users/usagi/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1532:494
    at m._executeEdit (file:///C:/Users/usagi/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1531:546)
    at m.type (file:///C:/Users/usagi/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1532:275)
    at file:///C:/Users/usagi/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1584:829
    at y._withViewEventsCollector (file:///C:/Users/usagi/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1586:518)
    at y._executeCursorEdit (file:///C:/Users/usagi/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1584:431)
    at y.type (file:///C:/Users/usagi/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1584:794)
    at e._type (file:///C:/Users/usagi/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2295:898)
    at e.trigger (file:///C:/Users/usagi/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2295:134)
    at I.runCommand (file:///C:/Users/usagi/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1930:972)
    at handler (file:///C:/Users/usagi/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1897:702)
    at e.handler (file:///C:/Users/usagi/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1610:808)
    at d.invokeFunction (file:///C:/Users/usagi/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1651:817)
    at u._tryExecuteCommand (file:///C:/Users/usagi/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3944:968)
    at file:///C:/Users/usagi/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3944:717
```
---
- VSCode: 1.47.3
- Windows: 19041.421 (Primary language setting is en-US, add secondary is a+Japanese)
- Keyboard: [DYGMA RAISE (ISO or English/UK layout)](https://dygma.com/products/dygma-raise)
